### ISSUE TITLE
Error While executing the project 

### ISSUE THREAD

**Issue by fxviking** [jxblum/pivotal-gemfire-clientserver-examples#2]
I get the below error while executing the boot run . I tried adding the jetty server dependency but then the spring boot would fail. Any idea how I can fix this?

```
[error 2016/11/18 22:32:00.343 IST <main> tid=11] Jmx manager could not be started because org/eclipse/jetty/server/Handler
java.lang.NoClassDefFoundError: org/eclipse/jetty/server/Handler
        at com.gemstone.gemfire.management.internal.ManagementAgent.startHttpService(ManagementAgent.java:214)
        at com.gemstone.gemfire.management.internal.ManagementAgent.startAgent(ManagementAgent.java:113)
        at com.gemstone.gemfire.management.internal.SystemManagementService.startManager(SystemManagementService.java:467)
        at com.gemstone.gemfire.management.internal.beans.ManagementAdapter.handleCacheCreation(ManagementAdapter.java:188)
        at com.gemstone.gemfire.management.internal.beans.ManagementListener.handleEvent(ManagementListener.java:111)
        at com.gemstone.gemfire.distributed.internal.InternalDistributedSystem.notifyResourceEventListeners(InternalDistributedSystem.java:2245)
        at com.gemstone.gemfire.distributed.internal.InternalDistributedSystem.handleResourceEvent(InternalDistributedSystem.java:505)
        at com.gemstone.gemfire.internal.cache.GemFireCacheImpl.init(GemFireCacheImpl.java:1009)
        at com.gemstone.gemfire.internal.cache.GemFireCacheImpl.create(GemFireCacheImpl.java:682)
        at com.gemstone.gemfire.cache.CacheFactory.create(CacheFactory.java:182)
        at com.gemstone.gemfire.cache.CacheFactory.create(CacheFactory.java:229)
        at org.springframework.data.gemfire.CacheFactoryBean.createCache(CacheFactoryBean.java:356)
        at org.springframework.data.gemfire.CacheFactoryBean.resolveCache(CacheFactoryBean.java:250)
        at org.springframework.data.gemfire.CacheFactoryBean.init(CacheFactoryBean.java:191)
        at org.springframework.data.gemfire.CacheFactoryBean.getObject(CacheFactoryBean.java:178)
        at org.springframework.data.gemfire.CacheFactoryBean.getObject(CacheFactoryBean.java:88)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1600)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:254)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:187)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1213)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1053)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1018)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:834)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:467)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:756)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
        at io.pivotal.gemfire.main.SpringGemFireServerApplication.main(SpringGemFireServerApplication.java:53)
```

**Comment by jxblum** [comment]
Hi @fxviking -

I have not updated this sample with the latest dependencies in awhile.  Technically, Pivotal GemFire is not based on Jetty anymore (back to Tomcat).  Let me take a look and get this working again.

Thank you for the feedback and sorry for the inconvenience.

Cheers,
John

**Comment by jxblum** [comment]
Hi @fxviking -

This issue should be resolved now.  See [commit history](https://github.com/jxblum/pivotal-gemfire-clientserver-examples/commits/master) for more details.

I ran both the `spring-gemfire-clientserver` and `spring-gemfire-clientserver-xml` examples from my IDE as well as the command-line.  All worked as expected.  Please let me know if you have any more trouble.

Thanks,
John

**Comment by fxviking** [comment]
Hello @jxblum,

I still get the same error , below the stacktrace . 

```
[info 2016/11/21 10:19:00.703 IST <main> tid=11] Defaulting license-working-dir to current working directory "C:\GEMFIREEXAMPLE\pivotal-gemfire-clientserver-examples".

[info 2016/11/21 10:19:00.708 IST <main> tid=11] Licensing required 6 milliseconds.

[info 2016/11/21 10:19:00.734 IST <main> tid=11] Starting peer location for Distribution Locator on localhost/127.0.0.1[10334]

[info 2016/11/21 10:19:00.742 IST <main> tid=11] Starting Distribution Locator on localhost/127.0.0.1[10334]

[info 2016/11/21 10:19:01.941 IST <main> tid=11] GemFire P2P Listener started on  tcp:///156.150.119.152:26899

[info 2016/11/21 10:19:02.076 IST <PingSender> tid=35] locator localhost(null)<v0>:10334 member address is MC0XEP9C(SpringGemFireServerApplication):59105

[info 2016/11/21 10:19:09.095 IST <PingSender> tid=38] locator localhost(null)<v0>:10334 member address is MC0XEP9C(SpringGemFireServerApplication):59105

[info 2016/11/21 10:19:14.115 IST <main> tid=11] Membership: lead member is now MC0XEP9C(SpringGemFireServerApplication):59105

[info 2016/11/21 10:19:14.132 IST <main> tid=11] This member, MC0XEP9C(SpringGemFireServerApplication):59105, is becoming group coordinator.

[info 2016/11/21 10:19:14.143 IST <main> tid=11] Entered into membership with ID MC0XEP9C(SpringGemFireServerApplication)<v0>:59105.

[info 2016/11/21 10:19:14.147 IST <main> tid=11] Starting DistributionManager MC0XEP9C(SpringGemFireServerApplication)<v0>:59105.  (took 12338/ ms)

[info 2016/11/21 10:19:14.151 IST <main> tid=11] Initial (membershipManager) view =  [MC0XEP9C(SpringGemFireServerApplication)<v0>:59105{lead}]

[info 2016/11/21 10:19:14.155 IST <main> tid=11] Admitting member <MC0XEP9C(SpringGemFireServerApplication)<v0>:59105>. Now there are 1 non-admin member(s).

[info 2016/11/21 10:19:14.159 IST <main> tid=11] MC0XEP9C(SpringGemFireServerApplication)<v0>:59105 is the elder and the only member.

[info 2016/11/21 10:19:14.290 IST <main> tid=11] Did not hear back from any other system. I am the first one.

[info 2016/11/21 10:19:14.296 IST <main> tid=11] Starting server location for Distribution Locator on localhost/127.0.0.1[10334]

[info 2016/11/21 10:19:14.485 IST <main> tid=11] Initializing region _monitoringRegion_156.150.119.152<v0>59105

[info 2016/11/21 10:19:14.492 IST <main> tid=11] Initialization of region _monitoringRegion_156.150.119.152<v0>59105 completed

[error 2016/11/21 10:19:15.462 IST <main> tid=11] Jmx manager could not be started because org/eclipse/jetty/server/Handler
java.lang.NoClassDefFoundError: org/eclipse/jetty/server/Handler
        at com.gemstone.gemfire.management.internal.ManagementAgent.startHttpService(ManagementAgent.java:214)
        at com.gemstone.gemfire.management.internal.ManagementAgent.startAgent(ManagementAgent.java:113)
        at com.gemstone.gemfire.management.internal.SystemManagementService.startManager(SystemManagementService.java:467)
        at com.gemstone.gemfire.management.internal.beans.ManagementAdapter.handleCacheCreation(ManagementAdapter.java:188)
        at com.gemstone.gemfire.management.internal.beans.ManagementListener.handleEvent(ManagementListener.java:111)
        at com.gemstone.gemfire.distributed.internal.InternalDistributedSystem.notifyResourceEventListeners(InternalDistributedSystem.java:2245)
        at com.gemstone.gemfire.distributed.internal.InternalDistributedSystem.handleResourceEvent(InternalDistributedSystem.java:505)
        at com.gemstone.gemfire.internal.cache.GemFireCacheImpl.init(GemFireCacheImpl.java:1009)
        at com.gemstone.gemfire.internal.cache.GemFireCacheImpl.create(GemFireCacheImpl.java:682)
        at com.gemstone.gemfire.cache.CacheFactory.create(CacheFactory.java:182)
        at com.gemstone.gemfire.cache.CacheFactory.create(CacheFactory.java:229)
        at org.springframework.data.gemfire.CacheFactoryBean.createCache(CacheFactoryBean.java:356)
        at org.springframework.data.gemfire.CacheFactoryBean.resolveCache(CacheFactoryBean.java:250)
        at org.springframework.data.gemfire.CacheFactoryBean.init(CacheFactoryBean.java:191)
        at org.springframework.data.gemfire.CacheFactoryBean.getObject(CacheFactoryBean.java:178)
        at org.springframework.data.gemfire.CacheFactoryBean.getObject(CacheFactoryBean.java:88)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1606)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:254)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1289)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1258)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1094)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1059)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:467)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1128)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1022)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:512)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:735)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
        at io.pivotal.gemfire.main.SpringGemFireServerApplication.main(SpringGemFireServerApplication.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:506)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.server.Handler
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 52 more

[warn 2016/11/21 10:19:15.562 IST <main> tid=11] org/eclipse/jetty/server/Handler
java.lang.NoClassDefFoundError: org/eclipse/jetty/server/Handler
        at com.gemstone.gemfire.management.internal.ManagementAgent.startHttpService(ManagementAgent.java:214)
        at com.gemstone.gemfire.management.internal.ManagementAgent.startAgent(ManagementAgent.java:113)
        at com.gemstone.gemfire.management.internal.SystemManagementService.startManager(SystemManagementService.java:467)
        at com.gemstone.gemfire.management.internal.beans.ManagementAdapter.handleCacheCreation(ManagementAdapter.java:188)
        at com.gemstone.gemfire.management.internal.beans.ManagementListener.handleEvent(ManagementListener.java:111)
        at com.gemstone.gemfire.distributed.internal.InternalDistributedSystem.notifyResourceEventListeners(InternalDistributedSystem.java:2245)
        at com.gemstone.gemfire.distributed.internal.InternalDistributedSystem.handleResourceEvent(InternalDistributedSystem.java:505)
        at com.gemstone.gemfire.internal.cache.GemFireCacheImpl.init(GemFireCacheImpl.java:1009)
        at com.gemstone.gemfire.internal.cache.GemFireCacheImpl.create(GemFireCacheImpl.java:682)
        at com.gemstone.gemfire.cache.CacheFactory.create(CacheFactory.java:182)
        at com.gemstone.gemfire.cache.CacheFactory.create(CacheFactory.java:229)
        at org.springframework.data.gemfire.CacheFactoryBean.createCache(CacheFactoryBean.java:356)
        at org.springframework.data.gemfire.CacheFactoryBean.resolveCache(CacheFactoryBean.java:250)
        at org.springframework.data.gemfire.CacheFactoryBean.init(CacheFactoryBean.java:191)
        at org.springframework.data.gemfire.CacheFactoryBean.getObject(CacheFactoryBean.java:178)
        at org.springframework.data.gemfire.CacheFactoryBean.getObject(CacheFactoryBean.java:88)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1606)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:254)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1289)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1258)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1094)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1059)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:467)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1128)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1022)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:512)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:735)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
        at io.pivotal.gemfire.main.SpringGemFireServerApplication.main(SpringGemFireServerApplication.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:506)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.server.Handler
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 52 more

[info 2016/11/21 10:19:15.668 IST <main> tid=11] Initializing region PdxTypes

[info 2016/11/21 10:19:15.670 IST <main> tid=11] Initialization of region PdxTypes completed

[info 2016/11/21 10:19:15.733 IST <main> tid=11] Initializing region __PR

[info 2016/11/21 10:19:15.735 IST <main> tid=11] Initialization of region __PR completed

[info 2016/11/21 10:19:15.772 IST <main> tid=11] Partitioned Region /Factorials is born with prId=1 ident:#Factorials

[info 2016/11/21 10:19:16.044 IST <main> tid=11] Bridge server connection listener bound to address localhost/127.0.0.1:40404 with backlog 1,000.

[info 2016/11/21 10:19:16.062 IST <main> tid=11] ClientHealthMonitorThread maximum allowed time between pings: 60,000

[info 2016/11/21 10:19:16.084 IST <main> tid=11] CacheServer Configuration:   port=40404 max-connections=800 max-threads=0 notify-by-subscription=true socket-buffer-size=32768 maximum-time-between-pin
gs=60000 maximum-message-count=230000 message-time-to-live=180 eviction-policy=none capacity=1 overflow directory=. groups=[] loadProbe=ConnectionCountProbe loadPollInterval=5000 tcpNoDelay=true
```

**Comment by jxblum** [comment]
So, looking at your _stack trace_ more closely, this error is mostly benign, unless you need to run either [Pulse](http://gemfire.docs.pivotal.io/docs-gemfire/latest/tools_modules/pulse/chapter_overview.html) or start the [Management REST interface](http://gemfire.docs.pivotal.io/docs-gemfire/latest/tools_modules/gfsh/command-pages/connect.html) and/or the [Developer REST interface](http://gemfire.docs.pivotal.io/docs-gemfire/latest/rest_apps/chapter_overview.html).

This error occurs when GemFire tries to start the embedded HTTP service in a GemFire Server.  The HTTP service only starts if the GemFire `http-service-port` (System) property is set to a non-zero value (defaults to **7070**).  If you disable the HTTP service, you will definitely **not** see the error.

However, what is troubling here is that GemFire is searching for _Eclipse Jetty_.  GemFire has not used Jetty since 7.0.  From GemFire 8.0 onward, GemFire has been based on _Apache Tomcat_.  All the _Spring (Boot)_ based examples in this GitHub project are [based on _Spring Data GemFire_ `1.8.5.RELEASE`](https://github.com/jxblum/pivotal-gemfire-clientserver-examples/blob/master/pom.xml#L89), which is [based on GemFire 8.2.0](https://github.com/spring-projects/spring-data-gemfire/blob/1.8.5.RELEASE/gradle.properties#L5) at present (or see [here](https://github.com/spring-projects/spring-data-gemfire/wiki/Spring-Data-GemFire-to-GemFire-Version-Compatibility) for additional details).

I am curious to know how you are running these examples.  Are you running them from the command-line using Maven, or from within your IDE?

Also, could you please share your `CLASSPATH` of the running GemFire Server?

You should only see _Spring Boot_ `1.4.2.RELEASE`, _Spring Data GemFire_ `1.8.5.RELEASE` and _GemFire_ `8.2.0` on the CLASSPATH.

**Comment by fxviking** [comment]
hello, 
Sorry I did not mention that part in the first post itself. 
I have tried running Inside IDE( eclipse ) & from command line too, same error is thrown. But its only Linked to the JMX manager part.  I tried the native client application also, similar error is thrown there too.  

Just to be sure , I tried executing the Pivotal Gemfire examples, one using the JMXmanager, it works fine which i strange to me.  

I have attached the txt file contaning the classpath & other details while executing. 
[classpath_other details.txt](https://github.com/jxblum/pivotal-gemfire-clientserver-examples/files/605468/classpath_other.details.txt)

Do you think it could be linked to the maven local repo, shd i try deleting and build it again

**Comment by jxblum** [comment]
Hi @fxviking -

Something is very strange about the way you are running the `spring-gemfire-clientserver` example.  

After looking in your log file (`classpath_other_details.txt`), I am not quite certain how it is picking up the required JAR files (e.g. GemFire, SDG, etc) on the classpath to run the example, technically.  Your classpath is defined as...

```
Class Path:
  /C:/Users/a203833/Downloads/eclipse-java-neon-R-win32-x86_64/eclipse/plugins/org.eclipse.m2e.maven.runtime_1.7.0.20160603-1931/jars/plexus-classworlds-2.5.2.jar
```

My guess is that perhaps this JAR file ("plexus-classworlds-2.5.2.jar") is a "fat" JAR created by Eclipse based on the project Maven POM and other IDE extensions.

The command to run the example was...

```
sun.java.command = org.codehaus.plexus.classworlds.launcher.Launcher -B spring-boot:run
```

Seems this "`org.codehaus.plexus.classworlds.launcher.Launcher`" class is a special class using a custom Java `ClassLoader` that knows how to read the contents of a "fat" JAR and find the bundled application libs (JARS) in the "fat" JAR to be included on the application's classpath at runtime.

I would view the contents of this JAR file.  I would also venture to guess that multiple GemFire JAR files maybe contained in this "fat" application JAR.  Again, Jetty is not used in GemFire anymore, and is definitely not used in the version of GemFire (i.e. 8.2.0) used by this example.

Thanks,
John

**Comment by fxviking** [comment]
hello, 
       I tried to make a sample project using Spring boot, Spring -data-gemfire, & Spring JPA. But I am stuck in a Null pointer exception . I used the the strcture as yours mostly only I have used a CRUDRepository , since my Value are in a DB existing  . I tried using both GemFireRepositiry & Crudrepository, but i get the repository which is autowired as null always inside my cache loader code.   Can you help and point out where i am going wrong . I have attached the sample project (not in it best form).  Or can you provide any examples or using gemfire with Gemfirerespository in Spring boot.   

I am using Java 8 & Maven 3.3 .  I have enabled a Scheduler to execute a method which will print the values. (There is a ScheduledExecutorService exception Debug which we can ignore , in the stack trace which i have attached). 

The main aim of my project is to see that the Data from DB is loaded in the cache. I am not sure if I need a Cache writer for this. 
[stack.txt](https://github.com/jxblum/pivotal-gemfire-clientserver-examples/files/609796/stack.txt)
[pivotal-gemfire-examples.zip](https://github.com/jxblum/pivotal-gemfire-clientserver-examples/files/609797/pivotal-gemfire-examples.zip)

**Comment by jxblum** [comment]
Hi @fxviking -

This will just be a quick follow-up response as I am out on PTO/Holiday.

The project I have most recently been working on is the [_Contacts Application_ RI](https://github.com/jxblum/contacts-application) (_Reference Implementation_ for SDG).  There is a [repository-example](https://github.com/jxblum/contacts-application/tree/master/repository-example) there that uses _Spring Boot_.  (In fact, all the examples use _Spring Boot_; sorry, I have yet to provide READMEs for the examples).

In the _repository-example_, there are a [bunch of different configurations](https://github.com/jxblum/contacts-application/tree/master/repository-example/src/main/java/example/app/config) that showcase different use cases (e.g. GemFire + JPA in a Global (JTA) TX).

Regarding...

> The main aim of my project is to see that the Data from DB is loaded in the cache.

In this case, you need a _GemFire_ [`CacheLoader`](http://data-docs-samples.cfapps.io/docs-gemfire/latest/javadocs/japi/com/gemstone/gemfire/cache/CacheLoader.html).  More details can be found [here](http://gemfire.docs.pivotal.io/docs-gemfire/latest/developing/outside_data_sources/sync_outside_data.html).

Finally, I took a quick peek at your application.  If you want a `DataSource` or, in your case, a `_Repository_`, to be "injected into an instance of the `CurrencyDBLoader`, then you need to declare it as a _Spring_ bean in your configuration.

Currently, you have this...

```
119:	 currencyRegionAttributes.setCacheLoader(new CurrencyDBLoader());
```

in the `currencyRegionAttributes` bean definition of the `SpringGemFireServerApplication` class...

```
	@Bean
	@SuppressWarnings({ "unchecked", "deprecation" })
	public RegionAttributesFactoryBean  currencyRegionAttributes() {
		RegionAttributesFactoryBean  currencyRegionAttributes = new RegionAttributesFactoryBean ();
	currencyRegionAttributes.setCacheLoader(new CurrencyDBLoader());
		currencyRegionAttributes.setCacheListener(new CurrencySubscriberListener());
		//currencyRegionAttributes.setKeyConstraint(Long.class);
		//currencyRegionAttributes.setValueConstraint(Currency.class);
		return currencyRegionAttributes;
	}

```

If you instantiate the `CurrencyDBLoader` directly, then the Spring container has not chance to provide the component (object instance) it's dependencies.  I.e., it won't be a "managed" bean managed by the _Spring_ container. 

Therefore you need to...

```
@Bean
public CurrencyDBLoader currenceyDbLoader() {
  return new CurrencyDbLoader();
}
```

And then either...

```
@Bean
public RegionAttributesFactoryBean currencyRegionAttributes(CurrencyDBLoader loader) {
  ...
  currencyRegionAttributes.setCacheLoader(loader);
  ...
}
```

Or...

```
@Bean RegionAttributesFactoryBean currencyRegionAttributes() {
   ...
   currencyRegionAttributes.setCacheLoader(currencyDbLoader())
   ...
}
```

Hope this helps!

**Comment by fxviking** [comment]
Thanks John , 
I will try your suggestions . 

 I have posted my query on the Pivotal about not specific to the above but more about the gemfire
https://discuss.pivotal.io/hc/en-us/community/posts/239415308-Gemfire-information-required-

In case you get time do reply .

Happy Holidays in advance!!
